Breast Cancer prediction using various ML classifiers

1. Importing Libraries

In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix,accuracy_score

2. Importing Dataset

In [2]:
df=pd.read_csv("/content/Dataset_master.xlsx - Breast Cancer Detection Classif.csv")
X=df.iloc[:,:-1].values
Y=df.iloc[:,-1].values

3.Checking for missing values

In [26]:
df.isnull().sum()

id                         0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
diagnosis                  0
dtype: int64

3. Splitting the dataset

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=42)

4. Feature Scaling

In [5]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)
print(X_train)

[[-0.23055943 -0.12348985 -0.29680142 ... -0.84082156 -0.8563616
  -0.76574773]
 [-0.2305946  -0.22826757 -0.65795149 ... -0.37706655 -1.3415819
  -0.41480748]
 [-0.2302707   0.14553402 -1.23056444 ... -0.04762652 -0.08997059
   0.4882635 ]
 ...
 [-0.16718429  0.03226081 -0.55578404 ... -1.26179013 -0.6828391
  -1.27672587]
 [-0.23025553 -0.05552593  0.10949242 ...  1.07924018  0.4755842
   1.25530227]
 [-0.23061433 -0.56525537  0.32333128 ... -0.61952313 -0.30366032
  -0.84348042]]


1. Logistic Regression

In [16]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression(random_state=42)
LR.fit(X_train,Y_train)
LR_pred=LR.predict(X_test)
print(confusion_matrix(LR_pred,Y_test))
print(accuracy_score(LR_pred,Y_test))

[[108   3]
 [  0  60]]
0.9824561403508771


2. KNN

In [27]:
from sklearn.neighbors import KNeighborsClassifier
KNN=KNeighborsClassifier(n_neighbors=13,metric='minkowski',p=2)
KNN.fit(X_train,Y_train)
KNN_pred=KNN.predict(X_test)
print(confusion_matrix(KNN_pred,Y_test))
LR_AS=accuracy_score(KNN_pred,Y_test)
print(LR_AS)

[[106   5]
 [  2  58]]
0.9590643274853801


3.SVM

In [29]:
from sklearn.svm import SVC
SVM=SVC(kernel='linear',random_state=42)
SVM.fit(X_train,Y_train)
SVM_pred=SVM.predict(X_test)
print(confusion_matrix(SVM_pred,Y_test))
SVM_AS=accuracy_score(SVM_pred,Y_test)
print(SVM_AS)

[[107   3]
 [  1  60]]
0.9766081871345029


4. Naive Bayes

In [31]:
from sklearn.naive_bayes import GaussianNB
NB=GaussianNB()
NB.fit(X_train,Y_train)
NB_pred=NB.predict(X_test)
print(confusion_matrix(NB_pred,Y_test))
NB_AS=accuracy_score(NB_pred,Y_test)
print(NB_AS)

[[105   6]
 [  3  57]]
0.9473684210526315


5. Decision Tree

In [32]:
from sklearn.tree import DecisionTreeClassifier
DT=DecisionTreeClassifier(criterion='entropy',random_state=42)
DT.fit(X_train,Y_train)
DT_pred=DT.predict(X_test)
print(confusion_matrix(DT_pred,Y_test))
DT_AS=accuracy_score(DT_pred,Y_test)

[[107   5]
 [  1  58]]


6. Random Forest

In [33]:
from sklearn.ensemble import RandomForestClassifier
RF=RandomForestClassifier(n_estimators=18,criterion='entropy')
RF.fit(X_train,Y_train)
RF_pred=RF.predict(X_test)
print(confusion_matrix(RF_pred,Y_test))
RF_AS=accuracy_score(RF_pred,Y_test)
print(RF_AS)

[[107   4]
 [  1  59]]
0.9707602339181286
